### PR TITLE
Added option to use remote OVA instead

### PR DESCRIPTION
**Pull request by rhjensen79**
For me, to have the OVA local, don't make sense, so I added the option, to use remote OVA as well.
The url is static, and there os probably a more pretty way, to implement this, but this is working, and won't break the way you do it today. So I thought it was a nice option, for a cool project.

### CODE REVIEW

**Comment by saintdle** [comment]
I'll have to test this, I did actually deploy from URL originally but I found some issues with the OVA deployment getting stuck. Manual from the URL in VC worked, so I presumed it was something from the terraform vSphere provider, I guessed at the fact there is a @ in the URL Path might be causing an issue. So in the essence of getting things working, I just reverted to deploying from a local copy. 

Thanks for having a look at the code, I'll try and test soon :D

**Comment by rhjensen79** [comment]
No problem. 
Just wanted to add the option.
Jumping around on multiple machines, big binaries in my repo, is never a good option for me. 
So wing the option to use it remote, makes more sense imho.

I have had a couple of times, where the FAH UI don't start, after deployment. But I'm not sure, if it's related to the remote option or not. 
Also customization of the VM's with CPU and memory, don't happen until I do another apply. But that's for another issue :-)

**Comment by saintdle** [comment]
> No problem.
> Just wanted to add the option.
> Jumping around on multiple machines, big binaries in my repo, is never a good option for me.
> So wing the option to use it remote, makes more sense imho.
> 
> I have had a couple of times, where the FAH UI don't start, after deployment. But I'm not sure, if it's related to the remote option or not.
> Also customization of the VM's with CPU and memory, don't happen until I do another apply. But that's for another issue :-)

Still need to test this, I also have some code from a Hashicorp employee that should allow the dymanic selection between the two options depending on what is set in the tfvars file. 

Regarding the CPU/MEM, that's now accepted a [bug ](https://github.com/hashicorp/terraform-provider-vsphere/issues/1130)in the provider.

**Comment by saintdle** [comment]
I've spent some time working on this, the code is now more dynamic and works by looking at the values passed/set in the main tfvars file. 

The user now only needs to set either local or remote var, and the script will deploy as needed using the appropiate method. 

This removes the need to go into the FAH_Appliance folder and edit the main.tf file.

**Pull request closed without merging**
